# Generated by Django 2.2.7 on 2020-01-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
