# Generated by Django 2.2.7 on 2020-01-04 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usersignup_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSignUp',
        ),
    ]
