# Generated by Django 2.2.7 on 2020-01-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usersignup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
