# Generated by Django 2.2.7 on 2020-01-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200104_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
