# Generated by Django 2.2.7 on 2020-01-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200104_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='string',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserSignUp',
        ),
    ]
